api_platform:
    patch_formats:
        json: ['application/merge-patch+json']
    enable_swagger_ui: false
    enable_re_doc: true
    # Symfony inflector wrongly pluralizes "nodes_sources" to "nodes_sourcess"
    keep_legacy_inflector: true
    graphql:
        graphiql:
            enabled: false
    show_webby: false
    swagger:
        versions: [3]
    title:       "%env(string:APP_TITLE)%"
    description: "%env(string:APP_DESCRIPTION)%"
    version:     '%env(string:APP_VERSION)%'
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/GeneratedEntity'
            - '%kernel.project_dir%/vendor/roadiz/core-bundle/src/Entity'
            - '%kernel.project_dir%/vendor/rezozero/tree-walker/src'
            - '%kernel.project_dir%/config/api_resources'

    collection:
        pagination:
            page_parameter_name: page
            items_per_page_parameter_name: itemsPerPage

    http_cache:
        invalidation:
            enabled: true
            varnish_urls: [ '%env(VARNISH_URL)%' ]

    defaults:
        enable_max_depth: true
        normalization_context:
            skip_null_values: true
        pagination_client_items_per_page: true
        pagination_items_per_page: 15
        pagination_maximum_items_per_page: 50
        cache_headers:
            etag: true
            public: true
            max_age: '%env(int:HTTP_CACHE_MAX_AGE)%'
            shared_max_age: '%env(int:HTTP_CACHE_SHARED_MAX_AGE)%'
            vary: [ 'Accept', 'Authorization', 'Origin', 'Accept-Encoding', 'Content-Type' ]
