rollerworks_password_strength:
    blacklist:
        default_provider: rollerworks_password_strength.blacklist.provider.chain
        providers:
            chain:
                lazy: true
                providers:
                    - RZ\Roadiz\CoreBundle\Security\Blacklist\Top500Provider
