twig:
    default_path: '%kernel.project_dir%/vendor/roadiz/rozier/src/Resources/views'
    strict_variables: false
    paths:
        '%kernel.project_dir%/vendor/roadiz/rozier/src/Resources/views': Rozier
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/vendor/roadiz/documents/src/Roadiz/Resources/views': ~

when@test:
    twig:
        strict_variables: false
