---
RZ\Roadiz\CoreBundle\Entity\AttributeValue:
    collectionOperations:
        get:
            method: "GET"
            normalization_context:
                groups: ["urls", "attribute", "document_display", "attribute_node", "attribute_documents"]
                enable_max_depth: true
    itemOperations:
        get:
            method: 'GET'
            normalization_context:
                groups: ["urls", "attribute", "document_display", "attribute_node", "attribute_documents"]
                enable_max_depth: true

