---
RZ\Roadiz\CoreBundle\Entity\NodesSources:
    iri: NodesSources
    shortName: NodesSources
    collectionOperations:
        get:
            method: "GET"
            normalization_context:
                groups:
                    - nodes_sources_base
                    - nodes_sources_default
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - position
        archives:
            method: 'GET'
            path: '/nodes_sources/archives'
            pagination_enabled: false
            pagination_client_enabled: false
            archive_enabled: true
            archive_publication_field_name: publishedAt
            normalization_context:
                groups:
                    - get
                    - archives
            openapi_context:
                summary: Get available NodesSources archives
                parameters: ~
                description: |
                    Get available NodesSources archives (years and months) based on their `publishedAt` field
        search:
            method: 'GET'
            path: '/nodes_sources/search'
            controller: RZ\Roadiz\CoreBundle\Api\Controller\NodesSourcesSearchController
            read: false
            normalization_context:
                groups:
                    - get
                    - nodes_sources_base
                    - nodes_sources_default
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
            openapi_context:
                summary: Search NodesSources resources
                description: |
                    Search all website NodesSources resources using **Solr** full-text search engine
                parameters:
                    -   type: string
                        name: search
                        in: query
                        required: true
                        description: Search pattern
                        schema:
                            type: string
    itemOperations:
        get:
            method: 'GET'
            normalization_context:
                groups: ["nodes_sources", "urls", "tag_base", "translation_base", "document_display"]
