---
RZ\Roadiz\CoreBundle\Entity\NodesSources:
    iri: NodesSources
    shortName: NodesSources
    collectionOperations:
        get:
            method: "GET"
            normalization_context:
                groups: ["nodes_sources_base", "urls", "tag_base", "translation_base", "document_display"]

    itemOperations:
        get:
            method: 'GET'
            normalization_context:
                groups: ["nodes_sources", "urls", "tag_base", "translation_base", "document_display"]
