---
RZ\Roadiz\CoreBundle\Entity\NodesSources:
    iri: NodesSources
    shortName: NodesSources
    collectionOperations:
        get:
            method: "GET"
            normalization_context:
                groups:
                    - nodes_sources_base
                    - nodes_sources_default
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
                    - position
        search:
            method: 'GET'
            path: '/nodes_sources/search'
            controller: RZ\Roadiz\CoreBundle\Api\Controller\NodesSourcesSearchController
            read: false
            normalization_context:
                groups:
                    - get
                    - nodes_sources_base
                    - nodes_sources_default
                    - urls
                    - tag_base
                    - translation_base
                    - document_display
            openapi_context:
                summary: Search NodesSources resources
                description: |
                    Search all website NodesSources resources using **Solr** full-text search engine
                parameters:
                    -   type: string
                        name: search
                        in: query
                        required: true
                        description: Search pattern
                        schema:
                            type: string
    itemOperations:
        get:
            method: 'GET'
            normalization_context:
                groups: ["nodes_sources", "urls", "tag_base", "translation_base", "document_display"]
